### ISSUE TITLE
Sign up for a DOI

### ISSUE THREAD

**Issue by a-torgovitsky** [conroylau/mivcausal#1]
https://guides.github.com/activities/citable-code/

**Comment by conroylau** [comment]
Done! The DOI badge is added to the `README` in commit https://github.com/conroylau/mivcausal/commit/dcb354f5d2c89675d722b92450df371330165668.

**Comment by a-torgovitsky** [comment]
Great!
The bibtex on the Zenodo website comes up like this
```
@software{conroylau_2020_4031964,
  author       = {conroylau},
  title        = {conroylau/mivcausal: First release},
  month        = sep,
  year         = 2020,
  publisher    = {Zenodo},
  version      = {v1.0.0},
  doi          = {10.5281/zenodo.4031964},
  url          = {https://doi.org/10.5281/zenodo.4031964}
}
```

Is there a way to fix the author and title fields?

**Comment by conroylau** [comment]
Done! Just fixed the author and title fields.
There is an optional field for the author's ORCID.
May I know do you have one?

Thanks!

**Comment by a-torgovitsky** [comment]
I do not have one
